version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000" # Nginx exposes 80, mapped to localhost:3000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=mongodb+srv://samplesudharsan4:aLIqH9LLjXOwC25F@cluster0.ptyub.mongodb.net/test
    restart: unless-stopped
